# Generated by Django 4.1.7 on 2023-03-15 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='Ссылка на контент')),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.upload', verbose_name='Лики к контенту')),
            ],
            options={
                'verbose_name': 'Ссылка на контент',
                'verbose_name_plural': 'Ссылки на контент',
            },
        ),
    ]
