# Generated by Django 4.1.7 on 2023-03-15 18:52

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('main', '0002_contentlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentlinks',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='contentlinks',
            name='upload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.upload', verbose_name='Линки к контенту'),
        ),
    ]
