# Generated by Django 4.1.7 on 2023-03-16 09:27

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('main', '0003_contentlinks_tags_alter_contentlinks_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'verbose_name': 'Ссылка на контент', 'verbose_name_plural': 'Ссылки на контент'},
        ),
        migrations.AddField(
            model_name='upload',
            name='link',
            field=models.TextField(default=0, verbose_name='Ссылка на контент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='ContentLinks',
        ),
    ]
